// AUTO-GENERATED by tools/build-image-manifest.js — do not edit.
// Add/remove files in images/<project-id>/ and re-run the script.
window.IMAGE_MANIFEST = {
  "about": {
    "hero": "images/about/hero.jpg"
  },
  "bethlehem-culinary": {
    "tile": "images/bethlehem-culinary/tile.jpg",
    "gallery": [
      {
        "src": "images/bethlehem-culinary/01.jpg"
      },
      {
        "src": "images/bethlehem-culinary/02.jpg"
      },
      {
        "src": "images/bethlehem-culinary/03.jpg"
      }
    ],
    "book": [
      {
        "src": "images/bethlehem-culinary/book-01.jpg",
        "caption": "Portfolio spread — site analysis: the culinary-school gap in the region, vehicular access, and the greenway connection."
      },
      {
        "src": "images/bethlehem-culinary/book-02.jpg",
        "caption": "Portfolio spread — program section: market, teaching, cooking, and event space stacked around central circulation."
      },
      {
        "src": "images/bethlehem-culinary/book-03.jpg",
        "caption": "Portfolio spread — concept development: defining, splitting, and stacking the band that organizes the building."
      },
      {
        "src": "images/bethlehem-culinary/book-04.jpg",
        "caption": "Portfolio spread — sectional model in basswood and acrylic."
      }
    ]
  },
  "bethlehem-riverfront": {
    "tile": "images/bethlehem-riverfront/tile.jpg",
    "gallery": [
      {
        "src": "images/bethlehem-riverfront/01.jpg"
      },
      {
        "src": "images/bethlehem-riverfront/02.jpg"
      }
    ],
    "book": [
      {
        "src": "images/bethlehem-riverfront/book-01.jpg",
        "caption": "Portfolio spread — connecting two sides of a river: site and trail-network analysis."
      },
      {
        "src": "images/bethlehem-riverfront/book-02.jpg",
        "caption": "Portfolio spread — circulation expansion: linking the D&L Trail, the Greenway, and the proposed riverfront path."
      },
      {
        "src": "images/bethlehem-riverfront/book-03.jpg",
        "caption": "Portfolio spread — form concept and circulation development: four speeds of movement through the park."
      },
      {
        "src": "images/bethlehem-riverfront/book-04.jpg",
        "caption": "Portfolio spread — riverfront detail: market, performance venue, dog park, waterfront seating."
      },
      {
        "src": "images/bethlehem-riverfront/book-05.jpg",
        "caption": "Portfolio spread — final model, perspective views."
      }
    ]
  },
  "craft": {
    "gallery": [
      {
        "src": "images/craft/01.jpg"
      },
      {
        "src": "images/craft/02.jpg"
      },
      {
        "src": "images/craft/03.jpg"
      },
      {
        "src": "images/craft/04.jpg"
      },
      {
        "src": "images/craft/05.jpg"
      }
    ]
  },
  "dissection": {
    "tile": "images/dissection/tile.jpg",
    "gallery": [
      {
        "src": "images/dissection/01.png",
        "caption": "First pass — pure Make2D linework, the object cut by three section planes."
      },
      {
        "src": "images/dissection/02.png",
        "caption": "Second pass — hatch and tone begin separating solid from cut surface."
      },
      {
        "src": "images/dissection/03.png",
        "caption": "Final drawing — color splits skin, section cut, and interior void."
      }
    ]
  },
  "exhibition-trailer": {
    "tile": "images/exhibition-trailer/tile.jpg",
    "gallery": [
      {
        "src": "images/exhibition-trailer/01.jpg",
        "caption": "MiiR Exhibition Trailer, deployed — recycled-timber skin over glulam structure, fold-out deck."
      },
      {
        "src": "images/exhibition-trailer/02.jpg",
        "caption": "Night. The moon-roof and interior glow turn the enclosure into a lantern."
      },
      {
        "src": "images/exhibition-trailer/03.jpg",
        "caption": "Kit of parts — exploded axonometric and the trailer in transport configuration."
      },
      {
        "src": "images/exhibition-trailer/04.jpg",
        "caption": "Interior — exhibition surfaces, moon-roof, warm neutrals."
      },
      {
        "src": "images/exhibition-trailer/05.jpg",
        "caption": "Elevations."
      },
      {
        "src": "images/exhibition-trailer/06.jpg",
        "caption": "Sections — the demountable enclosure over a stock gooseneck chassis."
      },
      {
        "src": "images/exhibition-trailer/07.jpg",
        "caption": "Plan — front room, exhibition space, fold-down tail bench."
      },
      {
        "src": "images/exhibition-trailer/08.jpg",
        "caption": "Section render."
      },
      {
        "src": "images/exhibition-trailer/09.jpg",
        "caption": "Section render."
      },
      {
        "src": "images/exhibition-trailer/10.mp4",
        "video": true,
        "caption": "Animation."
      },
      {
        "src": "images/exhibition-trailer/11.mp4",
        "video": true,
        "caption": "Animation."
      }
    ]
  },
  "feasibility": {
    "tile": "images/feasibility/tile.jpg",
    "gallery": [
      {
        "src": "images/feasibility/01.png",
        "caption": "Chat component spec — every state, every value, mapped to design-system tokens before hand-off to engineering."
      },
      {
        "src": "images/feasibility/02.png",
        "caption": "Zoning report module — bulk & use controls with rule-change diffing; detail collapsed one layer down so the table stays scannable."
      }
    ]
  },
  "mesa-verde": {
    "tile": "images/mesa-verde/tile.jpg",
    "gallery": [
      {
        "src": "images/mesa-verde/01.jpg"
      },
      {
        "src": "images/mesa-verde/02.jpg"
      },
      {
        "src": "images/mesa-verde/03.jpg"
      },
      {
        "src": "images/mesa-verde/04.jpg"
      },
      {
        "src": "images/mesa-verde/05.jpg"
      }
    ]
  },
  "one-room-schoolhouse": {
    "tile": "images/one-room-schoolhouse/tile.jpg",
    "gallery": [
      {
        "src": "images/one-room-schoolhouse/01.jpg"
      },
      {
        "src": "images/one-room-schoolhouse/02.jpg"
      },
      {
        "src": "images/one-room-schoolhouse/03.jpg"
      }
    ],
    "book": [
      {
        "src": "images/one-room-schoolhouse/book-01.jpg",
        "caption": "Portfolio spread — site placement on the Lehigh green: circulation, accessibility, external visibility."
      },
      {
        "src": "images/one-room-schoolhouse/book-02.jpg",
        "caption": "Portfolio spread — primary, secondary, and tertiary form studies; form emphasis through skin."
      },
      {
        "src": "images/one-room-schoolhouse/book-03.jpg",
        "caption": "Portfolio spread — final model: the faceted roof over a cross-shaped plan on the sloped site."
      }
    ]
  },
  "pastoral-urbanity": {
    "tile": "images/pastoral-urbanity/tile.jpg",
    "gallery": [
      {
        "src": "images/pastoral-urbanity/01.jpg"
      },
      {
        "src": "images/pastoral-urbanity/02.jpg"
      },
      {
        "src": "images/pastoral-urbanity/03.jpg"
      },
      {
        "src": "images/pastoral-urbanity/04.jpg"
      },
      {
        "src": "images/pastoral-urbanity/05.jpg"
      }
    ]
  },
  "singular-flow": {
    "tile": "images/singular-flow/tile.jpg",
    "gallery": [
      {
        "src": "images/singular-flow/01.jpg"
      },
      {
        "src": "images/singular-flow/02.jpg"
      },
      {
        "src": "images/singular-flow/03.jpg"
      }
    ],
    "book": [
      {
        "src": "images/singular-flow/book-01.jpg",
        "caption": "Portfolio spread — unit development, the red-tab connection system, and density-of-form studies."
      },
      {
        "src": "images/singular-flow/book-02.jpg",
        "caption": "Portfolio spread — final model in shot-sheet paper; the form read from multiple orientations."
      }
    ]
  },
  "unit-multiplication": {
    "tile": "images/unit-multiplication/tile.jpg",
    "gallery": [
      {
        "src": "images/unit-multiplication/01.jpg"
      },
      {
        "src": "images/unit-multiplication/02.jpg"
      },
      {
        "src": "images/unit-multiplication/03.jpg"
      }
    ],
    "book": [
      {
        "src": "images/unit-multiplication/book-01.jpg",
        "caption": "Portfolio spread — unit development and construction: fold lines, subtracted voids, opening variation."
      },
      {
        "src": "images/unit-multiplication/book-02.jpg",
        "caption": "Portfolio spread — connecting the units: brass fasteners, offset rows, and directions of flow."
      },
      {
        "src": "images/unit-multiplication/book-03.jpg",
        "caption": "Portfolio spread — final field model in bristol paper and brass fasteners, with detail views."
      }
    ]
  }
};
