// AUTO-GENERATED by tools/build-image-manifest.js — do not edit.
// Add/remove files in images/<project-id>/ and re-run the script.
window.IMAGE_MANIFEST = {
  "about": {
    "hero": "images/about/hero.jpg"
  },
  "bethlehem-culinary": {
    "tile": "images/bethlehem-culinary/tile.jpg",
    "gallery": [
      {
        "src": "images/bethlehem-culinary/01.jpg"
      },
      {
        "src": "images/bethlehem-culinary/02.jpg"
      },
      {
        "src": "images/bethlehem-culinary/03.jpg"
      }
    ]
  },
  "bethlehem-riverfront": {
    "tile": "images/bethlehem-riverfront/tile.jpg",
    "gallery": [
      {
        "src": "images/bethlehem-riverfront/01.jpg"
      },
      {
        "src": "images/bethlehem-riverfront/02.jpg"
      }
    ]
  },
  "craft": {
    "gallery": [
      {
        "src": "images/craft/01.jpg"
      },
      {
        "src": "images/craft/02.jpg"
      },
      {
        "src": "images/craft/03.jpg"
      },
      {
        "src": "images/craft/04.jpg"
      },
      {
        "src": "images/craft/05.jpg"
      }
    ]
  },
  "dissection": {
    "tile": "images/dissection/tile.jpg",
    "gallery": [
      {
        "src": "images/dissection/01.png",
        "caption": "First pass — pure Make2D linework, the object cut by three section planes."
      },
      {
        "src": "images/dissection/02.png",
        "caption": "Second pass — hatch and tone begin separating solid from cut surface."
      },
      {
        "src": "images/dissection/03.png",
        "caption": "Final drawing — color splits skin, section cut, and interior void."
      }
    ]
  },
  "exhibition-trailer": {
    "tile": "images/exhibition-trailer/tile.jpg",
    "gallery": [
      {
        "src": "images/exhibition-trailer/01.jpg",
        "caption": "MiiR Exhibition Trailer, deployed — recycled-timber skin over glulam structure, fold-out deck."
      },
      {
        "src": "images/exhibition-trailer/02.jpg",
        "caption": "Night. The moon-roof and interior glow turn the enclosure into a lantern."
      },
      {
        "src": "images/exhibition-trailer/03.jpg",
        "caption": "Kit of parts — exploded axonometric and the trailer in transport configuration."
      },
      {
        "src": "images/exhibition-trailer/04.jpg",
        "caption": "Interior — exhibition surfaces, moon-roof, warm neutrals."
      },
      {
        "src": "images/exhibition-trailer/05.jpg",
        "caption": "Elevations."
      },
      {
        "src": "images/exhibition-trailer/06.jpg",
        "caption": "Sections — the demountable enclosure over a stock gooseneck chassis."
      },
      {
        "src": "images/exhibition-trailer/07.jpg",
        "caption": "Plan — front room, exhibition space, fold-down tail bench."
      },
      {
        "src": "images/exhibition-trailer/08.jpg",
        "caption": "Section render."
      },
      {
        "src": "images/exhibition-trailer/09.jpg",
        "caption": "Section render."
      },
      {
        "src": "images/exhibition-trailer/10.mp4",
        "video": true,
        "caption": "Animation."
      },
      {
        "src": "images/exhibition-trailer/11.mp4",
        "video": true,
        "caption": "Animation."
      }
    ]
  },
  "feasibility": {
    "tile": "images/feasibility/tile.jpg",
    "gallery": [
      {
        "src": "images/feasibility/01.png",
        "caption": "Chat component spec — every state, every value, mapped to design-system tokens before hand-off to engineering."
      },
      {
        "src": "images/feasibility/02.png",
        "caption": "Zoning report module — bulk & use controls with rule-change diffing; detail collapsed one layer down so the table stays scannable."
      }
    ]
  },
  "mesa-verde": {
    "tile": "images/mesa-verde/tile.jpg",
    "gallery": [
      {
        "src": "images/mesa-verde/01.jpg"
      },
      {
        "src": "images/mesa-verde/02.jpg"
      },
      {
        "src": "images/mesa-verde/03.jpg"
      },
      {
        "src": "images/mesa-verde/04.jpg"
      },
      {
        "src": "images/mesa-verde/05.jpg"
      }
    ]
  },
  "one-room-schoolhouse": {
    "tile": "images/one-room-schoolhouse/tile.jpg",
    "gallery": [
      {
        "src": "images/one-room-schoolhouse/01.jpg"
      },
      {
        "src": "images/one-room-schoolhouse/02.jpg"
      },
      {
        "src": "images/one-room-schoolhouse/03.jpg"
      }
    ]
  },
  "pastoral-urbanity": {
    "tile": "images/pastoral-urbanity/tile.jpg",
    "gallery": [
      {
        "src": "images/pastoral-urbanity/01.jpg"
      },
      {
        "src": "images/pastoral-urbanity/02.jpg"
      },
      {
        "src": "images/pastoral-urbanity/03.jpg"
      },
      {
        "src": "images/pastoral-urbanity/04.jpg"
      },
      {
        "src": "images/pastoral-urbanity/05.jpg"
      }
    ]
  },
  "singular-flow": {
    "tile": "images/singular-flow/tile.jpg",
    "gallery": [
      {
        "src": "images/singular-flow/01.jpg"
      },
      {
        "src": "images/singular-flow/02.jpg"
      },
      {
        "src": "images/singular-flow/03.jpg"
      }
    ]
  },
  "unit-multiplication": {
    "tile": "images/unit-multiplication/tile.jpg",
    "gallery": [
      {
        "src": "images/unit-multiplication/01.jpg"
      },
      {
        "src": "images/unit-multiplication/02.jpg"
      },
      {
        "src": "images/unit-multiplication/03.jpg"
      }
    ]
  }
};
