#!/usr/bin/env python3
# Re-extract the Algoma component-catalog slides into wireframes-data.js.
#
# Source of truth: "Algoma Wireframes/platform-components-case-study.html"
# (Andy's Algoma-branded standalone mockup). Whenever he drops new/updated
# raw HTML components into a slide's <div class="slide-stage"> there, run:
#
#     python3 portfolio/tools/extract-wireframe-slides.py
#
# and the lachler.com WireframeComponentsPage picks them up on next load.
# The carousel auto-scales any stage content to fit (fitAll in StudyKit.jsx),
# so dropped-in components need no sizing work. Stages left empty render as
# a dashed "state mock — in progress" frame.
#
# Requires beautifulsoup4 (pip install beautifulsoup4 --break-system-packages).
import json, os, re, collections
from bs4 import BeautifulSoup

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SRC = os.path.join(ROOT, "Algoma Wireframes", "platform-components-case-study.html")
OUT = os.path.join(ROOT, "portfolio", "wireframes-data.js")

soup = BeautifulSoup(open(SRC).read(), "html.parser")

series = []
for sec in soup.find_all("section"):
    lab = sec.find(class_="sec-label")
    if not lab or "Component Series" not in lab.get_text():
        continue
    h2 = sec.find("h2").get_text(" ", strip=True)
    lead = sec.find("p", class_="lead")
    lead = lead.get_text(" ", strip=True) if lead else ""
    car = sec.find(class_="carousel")
    car_title = car.find(class_="car-title").get_text(" ", strip=True) if car else ""
    slides = []
    if car:
        for sl in car.find_all(class_="car-slide"):
            label_el = sl.find(class_="slide-label")
            n = label_el.find(class_="n").get_text(strip=True) if label_el.find(class_="n") else ""
            if label_el.find(class_="n"):
                label_el.find(class_="n").extract()
            label = label_el.get_text(" ", strip=True)
            cap = sl.find(class_="slide-caption")
            cap = cap.get_text(" ", strip=True) if cap else ""
            stage = sl.find(class_="slide-stage")
            stage_html = stage.decode_contents().strip() if stage else ""
            slides.append({"n": n, "label": label, "caption": cap, "stage": stage_html})
    impact = []
    for card in sec.find_all(class_="impact-card"):
        k = card.find(class_="k").get_text(strip=True)
        p = card.find("p").decode_contents().strip()
        impact.append({"k": k, "html": p})
    series.append({"label": lab.get_text(strip=True), "title": h2, "lead": lead,
                   "carTitle": car_title, "slides": slides, "impact": impact})

about = {
    "lead": "Every component that ships into the Algoma platform should answer three questions: what does it do, what new ability does it hand the user, and which growth goal does it serve. This catalog holds each design to that standard — with the full state set browsable in place, and the reasoning documented next to it.",
    "note": "Components are shown as working HTML prototypes at spec fidelity: real tokens, real spacing, real copy. What you see in the carousel is what engineering receives.",
}

js = "// AUTO-GENERATED by tools/extract-wireframe-slides.py — do not hand-edit.\n"
js += "// Source: Algoma Wireframes/platform-components-case-study.html\n"
js += "// Prototype HTML is preserved verbatim — components keep their shipped design.\n"
js += "window.WF_ABOUT = " + json.dumps(about) + ";\n"
js += "window.WF_SERIES = " + json.dumps(series) + ";\n"
open(OUT, "w").write(js)

for s in series:
    filled = sum(1 for sl in s["slides"] if len(sl["stage"]) > 60)
    print(f"{s['title']}: {len(s['slides'])} slides, {filled} filled")
classes = collections.Counter()
for s in series:
    for sl in s["slides"]:
        for m in re.findall(r'class="([^"]+)"', sl["stage"]):
            for c in m.split():
                classes[c] += 1
known = {"fit", "board", "board-item", "board-cap", "pair", "pair-arrow", "stack", "dv-oid"}
unknown = set(classes) - known
if unknown:
    print("NOTE — stage HTML uses classes with no CSS in StudyKit.jsx:", sorted(unknown))
    print("Add styles for them to the study-kit-css block or they'll render unstyled.")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
